### ISSUE TITLE
instalations issues, redirect does not work

### ISSUE THREAD

**Issue by mckaygerhard** [RealityRipple/squirrelmail#3]
i sued to made some steps as for older squirremail and after that login and redirect doe snot work...

i just said "you must be login to work"

ther's some aditional or different step in the installation process?

why the documentation are not updated? this it's php7 only project?

i can help with those task but i need first help!

**Comment by RealityRipple** [comment]
The only differentiation I can imagine getting in the way is from 1cd1fed06bfd0f26a78932ba129ecdd0c0147e08, where I use the `$provider_uri` config variable to assign the Content Security Policy. You may want to check your browser's Error Console (usually available through developer tools) and see if there's any CSP errors showing up. Otherwise, I'm going to need a little more information to go on.

**Comment by mckaygerhard** [comment]
well sorry for you i reported due seems not me are unique related to this problem.. 

debian package install and works perfectly and i use it! i'll will try in alpine linux alter but you must do some test..

**Comment by mckaygerhard** [comment]
ah i found your probolem seems you develop in guindows.. opufff
